create table if not exists public.user_backups (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create table if not exists public.reward_deliveries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  twitch_name text not null,
  player_name text,
  prize_type text not null check (prize_type in ('mp','mc','megavip')),
  amount integer not null check (amount > 0),
  status text not null,
  api_result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.user_backups enable row level security;
alter table public.reward_deliveries enable row level security;
create policy "backup_select_own" on public.user_backups for select to authenticated using ((select auth.uid())=user_id);
create policy "backup_insert_own" on public.user_backups for insert to authenticated with check ((select auth.uid())=user_id);
create policy "backup_update_own" on public.user_backups for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create policy "delivery_select_own" on public.reward_deliveries for select to authenticated using ((select auth.uid())=user_id);
create policy "delivery_insert_own" on public.reward_deliveries for insert to authenticated with check ((select auth.uid())=user_id);
