(function(){
  "use strict";
  const $=id=>document.getElementById(id);
  const KEY="tw_bits_wheel_v1";
  const defaults={enabled:false,bitsPerTier:100,spinsPerTier:1,accumulate:true,maxSpins:20,spinDuration:8,gapSeconds:3,displayMode:"on_bits",duringGiveaway:"wait",hideDelay:8,sendChat:true,summary:true,history:true,repeat:true,prizes:[{id:"p1",name:"Ancient Box",chance:25,color:"#9146ff",active:true},{id:"p2",name:"10x Talismã",chance:25,color:"#00e5ff",active:true},{id:"p3",name:"Garuda Feather",chance:20,color:"#00e676",active:true},{id:"p4",name:"Prêmio Surpresa",chance:15,color:"#ffca28",active:true},{id:"p5",name:"Tente novamente",chance:15,color:"#e91e63",active:true}],queue:[],history:[],remainders:{},processedIds:[],paused:false,lastCompleted:null};
  let data=load(),processing=false,current=null,spinTimer=null;
  function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")};}catch(_){return structuredClone(defaults)}}
  function save(){localStorage.setItem(KEY,JSON.stringify(data));window.salvarNuvem?.();renderAll();window.dispatchEvent(new CustomEvent("megaloot:bits-wheel-state"));const pub=window.publishMegaLootOverlayState?.(true);const st=$("bw-sync-status");if(st){st.textContent=`Estado enviado: ${current?.phase||"espera"} · ${new Date().toLocaleTimeString("pt-BR")}`;}return pub;}
  function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
  function id(){return crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}
  function later(fn,ms){
    try{const due=Date.now()+ms,blob=new Blob([`onmessage=e=>setTimeout(()=>postMessage(1),Math.max(0,e.data-Date.now()))`],{type:"text/javascript"}),url=URL.createObjectURL(blob),w=new Worker(url);w.onmessage=()=>{w.terminate();URL.revokeObjectURL(url);fn()};w.postMessage(due);return w}catch(_){return setTimeout(fn,ms)}
  }
  function activePrizes(){return data.prizes.filter(p=>p.active&&Number(p.chance)>0)}
  function totalChance(){return activePrizes().reduce((a,p)=>a+Number(p.chance||0),0)}
  function settingsFromUI(){
    data.enabled=!!$("bw-enabled")?.checked;data.bitsPerTier=Math.max(1,Number($("bw-bits-tier")?.value||100));data.spinsPerTier=Math.max(1,Number($("bw-spins-tier")?.value||1));data.accumulate=!!$("bw-accumulate")?.checked;data.maxSpins=Math.max(1,Number($("bw-max-spins")?.value||20));data.spinDuration=Math.max(3,Number($("bw-duration")?.value||8));data.gapSeconds=Math.max(0,Number($("bw-gap")?.value||3));data.displayMode=$("bw-display-mode")?.value||"on_bits";data.duringGiveaway=$("bw-during-giveaway")?.value||"wait";data.hideDelay=Math.max(1,Number($("bw-hide-delay")?.value||8));data.sendChat=!!$("bw-send-chat")?.checked;data.summary=!!$("bw-summary")?.checked;data.history=!!$("bw-history-enabled")?.checked;data.repeat=!!$("bw-repeat")?.checked;
  }
  function showTab(name,btn){document.querySelectorAll(".bw-pane").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".bw-tab").forEach(x=>x.classList.remove("active"));$("bw-pane-"+name)?.classList.add("active");btn?.classList.add("active");renderAll()}
  function buildPanel(){
    const card=document.createElement("div");card.className="config-card bw-launch-card";card.innerHTML='<label>🎡 Roleta de Bits</label><span class="config-desc">Giros automáticos por Cheers, brindes manuais, fila e histórico.</span><button class="btn-purple" onclick="openModal(\'bits-wheel-modal\')">ABRIR PAINEL DA ROLETA</button>';
    document.querySelector(".theme-launch-card")?.after(card);
    const modal=document.createElement("div");modal.id="bits-wheel-modal";modal.className="modal-overlay";modal.innerHTML=`<div class="modal-content modern-modal bw-shell"><div class="modern-head"><div class="modern-title"><i>🎡</i><div><h2>Roleta de Bits</h2><p>Giros automáticos, prêmios manuais e controle completo</p></div></div><button class="modern-close" onclick="closeModal('bits-wheel-modal')">&times;</button></div><div class="bw-tabs"><button class="bw-tab active" onclick="BitsWheel.tab('config',this)">⚙️ Configuração</button><button class="bw-tab" onclick="BitsWheel.tab('prizes',this)">🎁 Prêmios</button><button class="bw-tab" onclick="BitsWheel.tab('manual',this)">🎡 Giros manuais</button><button class="bw-tab" onclick="BitsWheel.tab('queue',this)">📋 Fila</button><button class="bw-tab" onclick="BitsWheel.tab('history',this)">🏆 Histórico</button></div><div class="bw-body">
    <section id="bw-pane-config" class="bw-pane active"><div class="mcard full bw-overlay-url-card"><label>URL EXCLUSIVA DA ROLETA NO OBS</label><div class="bw-url-row"><input id="bits-overlay-url" class="modern-input" readonly placeholder="A URL aparecerá após o login"><button class="modern-save" onclick="BitsWheel.copyUrl()">📋 COPIAR URL</button><button class="secondary-btn" onclick="BitsWheel.openUrl()">🔗 ABRIR</button></div><small>Use esta URL em uma nova Fonte de Navegador, separada do overlay do sorteador. O fundo é transparente.</small></div><div class="pane-head"><div><h3>Configuração da Roleta</h3><small>As alterações são salvas no navegador e no backup da conta</small></div><button class="modern-save" onclick="BitsWheel.saveSettings()">💾 SALVAR</button></div><div class="settings-grid"><div class="mcard full bw-toggle-card"><label class="checkbox-container"><input id="bw-enabled" type="checkbox"> <span><b>Ativar Roleta de Bits</b><small>Somente Cheers reais geram giros automáticos</small></span></label></div><div class="mcard"><label>BITS NECESSÁRIOS POR FAIXA</label><input id="bw-bits-tier" type="number" min="1"><label>GIROS CONCEDIDOS POR FAIXA</label><input id="bw-spins-tier" type="number" min="1"><div id="bw-rule-preview" class="bw-rule-preview"></div></div><div class="mcard"><label>LIMITE E TEMPO</label><input id="bw-max-spins" type="number" min="1" placeholder="Máximo de giros"><input id="bw-duration" type="number" min="3" placeholder="Duração do giro"><input id="bw-gap" type="number" min="0" placeholder="Intervalo entre giros"></div><div class="mcard"><label>EXIBIÇÃO NO OVERLAY</label><select id="bw-display-mode"><option value="on_bits">Mostrar somente ao receber Bits</option><option value="always">Manter sempre visível</option><option value="hidden">Ocultar do overlay</option></select><label>Durante o sorteio principal</label><select id="bw-during-giveaway"><option value="wait">Aguardar o sorteio terminar</option><option value="small">Mostrar em tamanho reduzido</option><option value="immediate">Mostrar imediatamente</option></select><label>Ocultar após o resultado</label><input id="bw-hide-delay" type="number" min="1"></div><div class="mcard"><label>COMPORTAMENTO</label><label class="checkbox-container"><input id="bw-accumulate" type="checkbox"> Acumular Bits restantes por usuário</label><label class="checkbox-container"><input id="bw-repeat" type="checkbox"> Permitir prêmios repetidos</label><label class="checkbox-container"><input id="bw-send-chat" type="checkbox"> Enviar resultados no chat</label><label class="checkbox-container"><input id="bw-summary" type="checkbox"> Mostrar resumo final</label><label class="checkbox-container"><input id="bw-history-enabled" type="checkbox"> Salvar no histórico</label></div></div></section>
    <section id="bw-pane-prizes" class="bw-pane"><div class="bw-two"><div class="creator"><h3>Novo prêmio</h3><input id="bw-prize-name" class="modern-input" placeholder="Nome do prêmio"><div class="field-row"><input id="bw-prize-chance" class="modern-input" type="number" min="0.01" step="0.01" placeholder="Chance %"><input id="bw-prize-color" type="color" value="#9146ff"></div><button class="modern-save" style="width:100%" onclick="BitsWheel.addPrize()">➕ ADICIONAR PRÊMIO</button></div><div><div class="pane-head"><div><h3>Prêmios cadastrados</h3><small id="bw-total-chance"></small></div><button class="secondary-btn" onclick="BitsWheel.normalize()">NORMALIZAR</button></div><div id="bw-prize-list" class="item-list"></div></div></div></section>
    <section id="bw-pane-manual" class="bw-pane"><div class="creator-grid"><div class="creator"><h3>Conceder giros de brinde</h3><input id="bw-manual-user" class="modern-input" placeholder="Usuário da Twitch"><input id="bw-manual-spins" class="modern-input" type="number" min="1" value="1"><input id="bw-manual-reason" class="modern-input" placeholder="Motivo, exemplo: brinde"><label class="checkbox-container"><input id="bw-manual-chat" type="checkbox" checked> Avisar no chat</label><button class="modern-save" style="width:100%" onclick="BitsWheel.manual()">🎁 ADICIONAR À FILA</button></div><div class="creator"><h3>Teste visual</h3><p class="config-desc">Não envia mensagem, não registra prêmio e não altera Bits.</p><button class="modern-save" style="width:100%" onclick="BitsWheel.test()">🧪 TESTAR ROLETA</button></div></div></section>
    <section id="bw-pane-queue" class="bw-pane"><div class="pane-head"><div><h3>Fila automática</h3><small id="bw-queue-count"></small><small id="bw-sync-status" style="display:block;color:#00e5ff;margin-top:4px">Sincronização pronta</small></div><div class="actions"><button class="secondary-btn" onclick="BitsWheel.pause()">⏯ PAUSAR / CONTINUAR</button><button class="danger-btn" onclick="BitsWheel.clearQueue()">LIMPAR</button></div></div><div id="bw-queue-list" class="item-list"></div></section>
    <section id="bw-pane-history" class="bw-pane"><div class="pane-head"><div><h3>Histórico da Roleta</h3><small>Todos os prêmios são de entrega manual</small></div><button class="danger-btn" onclick="BitsWheel.clearHistory()">LIMPAR HISTÓRICO</button></div><div id="bw-history-list" class="item-list"></div></section>
    </div></div>`;document.body.appendChild(modal);syncUI();renderAll();
  }
  function syncUI(){[["bw-enabled","enabled"],["bw-accumulate","accumulate"],["bw-repeat","repeat"],["bw-send-chat","sendChat"],["bw-summary","summary"],["bw-history-enabled","history"]].forEach(([i,k])=>{if($(i))$(i).checked=!!data[k]});[["bw-bits-tier","bitsPerTier"],["bw-spins-tier","spinsPerTier"],["bw-max-spins","maxSpins"],["bw-duration","spinDuration"],["bw-gap","gapSeconds"],["bw-hide-delay","hideDelay"]].forEach(([i,k])=>{if($(i))$(i).value=data[k]});if($("bw-display-mode"))$("bw-display-mode").value=data.displayMode;if($("bw-during-giveaway"))$("bw-during-giveaway").value=data.duringGiveaway}
  function renderAll(){if(!$("bits-wheel-modal"))return;const b=data.bitsPerTier,g=data.spinsPerTier;$("bw-rule-preview").innerHTML=`<b>${b} Bits = ${g} giro${g>1?'s':''}</b><small>${b*2} Bits = ${g*2} giros · ${b*3} Bits = ${g*3} giros</small>`;const total=totalChance();$("bw-total-chance").textContent=total===100?"✅ Distribuição válida: 100%":`⚠️ Total: ${total.toFixed(2)}%`;$("bw-total-chance").className=total===100?"ok":"warn";$("bw-prize-list").innerHTML=data.prizes.map(p=>`<article class="citem bw-prize-item"><span class="bw-color" style="background:${p.color}"></span><div class="hperson"><b>${esc(p.name)}</b><small>${Number(p.chance)}% de chance</small></div><label class="bw-switch"><input type="checkbox" ${p.active?'checked':''} onchange="BitsWheel.togglePrize('${p.id}',this.checked)"><span></span></label><button class="iaction" onclick="BitsWheel.removePrize('${p.id}')">🗑️</button></article>`).join('')||'<div class="history-empty">Nenhum prêmio cadastrado.</div>';$("bw-queue-count").textContent=`${data.queue.length} evento(s) · ${data.paused?'PAUSADA':'ATIVA'}`;$("bw-queue-list").innerHTML=(current?[queueCard(current,true)]:"")+data.queue.map(q=>queueCard(q,false)).join('')+(data.lastCompleted?queueCard({...data.lastCompleted,source:"CONCLUÍDO"},false):"")||'<div class="history-empty">Fila vazia.</div>';$("bw-history-list").innerHTML=data.history.slice().reverse().map(h=>`<article class="citem"><div class="citem-head"><span class="ctrigger">@${esc(h.user)} · ${h.bits||0} Bits</span><span class="meta">${new Date(h.time).toLocaleString('pt-BR')}</span></div><div class="cmessage">${h.results.map(x=>'🎁 '+esc(x)).join('<br>')}</div><div class="metas"><span class="meta">${h.spins} giros</span><span class="meta">Entrega manual</span></div></article>`).join('')||'<div class="history-empty">Nenhum giro registrado.</div>'}
  function queueCard(q,active){return `<article class="citem ${active?'bw-running':''}"><div class="citem-head"><span class="ctrigger">@${esc(q.user)}</span><span class="meta">${active?'GIRANDO AGORA':esc(q.source)}</span></div><div class="metas"><span class="meta">${q.bits||0} Bits</span><span class="meta">${q.spins} giros</span>${q.bonus?`<span class="meta">${q.bonus} brinde</span>`:''}</div></article>`}
  function pick(exclude){const ps=activePrizes().filter(p=>data.repeat||p.id!==exclude);let r=Math.random()*ps.reduce((a,p)=>a+Number(p.chance),0);for(const p of ps){r-=Number(p.chance);if(r<=0)return p}return ps.at(-1)}
  function wheelAngle(prize){const ps=activePrizes(),idx=ps.findIndex(p=>p.id===prize.id),seg=360/ps.length;return 1800+(360-(idx*seg+seg/2))}
  function publicState(){return {config:{enabled:data.enabled,bitsPerTier:data.bitsPerTier,spinsPerTier:data.spinsPerTier,displayMode:data.displayMode,hideDelay:data.hideDelay,duration:data.spinDuration,prizes:activePrizes().map(p=>({name:p.name,color:p.color,chance:p.chance}))},current:current?{...current}:null,queueLength:data.queue.length,paused:data.paused,lastCompleted:data.lastCompleted,heartbeat:Date.now()}}
  function enqueue(evt){if(!evt.spins||evt.spins<1)return;data.queue.push(evt);save();process()}
  function startDirectEvent(evt){
    if(spinTimer){try{clearTimeout(spinTimer)}catch(_){}try{spinTimer.terminate?.()}catch(_){}spinTimer=null}
    data.paused=false;data.queue=data.queue.filter(q=>!q.test);processing=true;current={...evt,index:0,results:[],phase:"intro",spinId:id()};save();
    later(()=>{if(current&&current.id===evt.id)runSpin()},900);
  }
  function process(){if(processing||data.paused||!data.queue.length||totalChance()!==100)return;if(!data.enabled&&!data.queue[0]?.test&&!String(data.queue[0]?.id||"").startsWith("manual:"))return;if(data.duringGiveaway==='wait'&&window.currentWinnerLogin){later(process,1500);return}processing=true;current=data.queue.shift();current.index=0;current.results=[];current.phase="intro";current.spinId=id();save();if(data.sendChat&&!current.test)sendChatMsg?.(`🎡 @${current.user} recebeu ${current.spins} giro${current.spins>1?'s':''} na Roleta de Bits!`);later(runSpin,1600)}
  function runSpin(){if(!current)return;if(current.index>=current.spins){finish();return}const prev=current.results.at(-1)?.id||null,p=pick(prev);if(!p){finish();return}current.phase="preparing";current.prize={id:p.id,name:p.name,color:p.color};current.angle=wheelAngle(p)+Math.random()*30-15;current.spinId=id();save();later(()=>{if(!current)return;current.phase="spinning";save();spinTimer=later(()=>{current.phase="result";current.results.push({id:p.id,name:p.name});current.index++;save();if(data.sendChat&&!current.test)sendChatMsg?.(`🎯 Giro ${current.index}/${current.spins}: @${current.user} ganhou ${p.name}!`);spinTimer=later(runSpin,data.gapSeconds*1000+1800)},data.spinDuration*1000)},350)}
  function finish(){if(!current)return;current.phase="summary";save();const done=current;if(data.summary&&data.sendChat&&!done.test){const counts={};done.results.forEach(r=>counts[r.name]=(counts[r.name]||0)+1);const text=Object.entries(counts).map(([n,c])=>`${c>1?c+'x ':''}${n}`).join(', ');sendChatMsg?.(`🏆 Resultado de @${done.user}: ${text}`)}if(data.history&&!done.test)data.history.push({user:done.user,bits:done.bits||0,spins:done.spins,results:done.results.map(r=>r.name),time:new Date().toISOString(),source:done.source});later(()=>{data.lastCompleted={...done,phase:"completed"};current=null;processing=false;save();later(process,250)},data.hideDelay*1000)}
  function cheer(msg){if(!data.enabled||!msg?.bits||msg.bits<1)return;const eventId=msg.messageId||`${msg.username}:${msg.bits}:${Date.now()}`;if(data.processedIds.includes(eventId))return;data.processedIds.push(eventId);data.processedIds=data.processedIds.slice(-300);const user=msg.displayName||msg.username||"Anônimo",key=(msg.username||"anonymous").toLowerCase();let total=Number(msg.bits)+(data.accumulate?Number(data.remainders[key]||0):0);const tiers=Math.floor(total/data.bitsPerTier);if(data.accumulate)data.remainders[key]=total%data.bitsPerTier;const spins=Math.min(data.maxSpins,tiers*data.spinsPerTier);if(spins>0)enqueue({id:eventId,user,bits:Number(msg.bits),spins,bonus:0,source:"Bits",test:false});else save()}
  function wrapChat(){const old=window.handleChatCommands;if(typeof old!=="function"||old.__bitsWrapped)return;const fn=function(msg){old.apply(this,arguments);cheer(msg)};fn.__bitsWrapped=true;window.handleChatCommands=fn}
  window.BitsWheel={tab:showTab,async copyUrl(){const v=$("bits-overlay-url")?.value;if(!v)return alert("Aguarde a sala do overlay ser criada.");await navigator.clipboard.writeText(v);alert("URL da Roleta copiada!")},openUrl(){const v=$("bits-overlay-url")?.value;if(v)window.open(v,"_blank","noopener")},saveSettings(){settingsFromUI();save();process()},addPrize(){const n=$("bw-prize-name").value.trim(),c=Number($("bw-prize-chance").value),color=$("bw-prize-color").value;if(!n||!c)return alert("Informe nome e porcentagem.");data.prizes.push({id:id(),name:n,chance:c,color,active:true});$("bw-prize-name").value="";$("bw-prize-chance").value="";save()},removePrize(pid){data.prizes=data.prizes.filter(p=>p.id!==pid);save()},togglePrize(pid,v){const p=data.prizes.find(x=>x.id===pid);if(p)p.active=v;save()},normalize(){const ps=activePrizes();if(!ps.length)return;const v=100/ps.length;ps.forEach((p,i)=>p.chance=i===ps.length-1?Number((100-v*(ps.length-1)).toFixed(2)):Number(v.toFixed(2)));save()},manual(){const user=$("bw-manual-user").value.trim().replace(/^@/,""),spins=Math.max(1,Number($("bw-manual-spins").value||1));if(!user)return alert("Informe o usuário.");const announce=$("bw-manual-chat").checked;enqueue({id:"manual:"+id(),user,bits:0,spins,bonus:spins,source:$("bw-manual-reason").value.trim()||"Brinde manual",test:false});if(announce)sendChatMsg?.(`🎁 @${user} recebeu ${spins} giro${spins>1?'s':''} extra${spins>1?'s':''} de brinde!`)},test(){const ps=activePrizes();if(!ps.length)return alert("Cadastre pelo menos um prêmio ativo antes do teste.");if(Math.abs(totalChance()-100)>0.001){const v=100/ps.length;ps.forEach((p,i)=>p.chance=i===ps.length-1?Number((100-v*(ps.length-1)).toFixed(2)):Number(v.toFixed(2)));}const evt={id:"test:"+id(),user:"MegaTester",bits:100,spins:1,bonus:0,source:"Teste visual",test:true};startDirectEvent(evt)},pause(){data.paused=!data.paused;save();if(!data.paused)process()},clearQueue(){if(confirm("Limpar os eventos aguardando?")){data.queue=[];save()}},clearHistory(){if(confirm("Limpar o histórico da roleta?")){data.history=[];save()}},getPublicState:publicState,cheer};
  document.addEventListener("DOMContentLoaded",()=>{buildPanel();setTimeout(wrapChat,1200);setInterval(()=>{wrapChat();process()},1000)});
})();
